[package]
name = "rootfm-core"
version = "0.1.0"
authors = ["Simon Wollwage <mail.wollwage@gmail.com>"]
edition = "2018"

[dev-dependencies]
midly = "*"
hound = "*"
cpal = "0.10"

[dependencies.libm]
version = "*"
